# use with export SPRING_PROFILES_ACTIVE=prod
# java -jar -Dspring.profiles.active=prod ecomm.jar
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecomm}
    username: ${SPRING_DATASOURCE_USERNAME:ecomm}
    password: ${SPRING_DATASOURCE_PASSWORD:T3st12E}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect