openapi: 3.0.0
info:
  title: Sample API
  description: API for managing products, purchase orders, and order items.
  version: 1.0.0

servers:
  - url: 'http://localhost:8080/api'

paths:
  /products:
    get:
      tags:
        - Product
      summary: Get a list of all products
      responses:
        '200':
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags:
        - Product
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created.

  /products/{id}:
    get:
      tags:
        - Product
      summary: Get a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single product.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      tags:
        - Product
      summary: Update an existing product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated.
    delete:
      tags:
        - Product
      summary: Delete a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Product deleted.

  /orders:
    get:
      tags:
        - Order
      summary: Get a list of all orders
      responses:
        '200':
          description: A list of orders.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseOrder'
    post:
      tags:
        - Order
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
      responses:
        '201':
          description: Order created.

  /orders/{id}:
    get:
      tags:
        - Order
      summary: Get an order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single order.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
    put:
      tags:
        - Order
      summary: Update an existing order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
      responses:
        '200':
          description: Order updated.
    delete:
      tags:
        - Order
      summary: Delete an order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Order deleted.

  /order-items:
    get:
      tags:
        - OrderItem
      summary: Get a list of all order items
      responses:
        '200':
          description: A list of order items.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderItem'
    post:
      tags:
        - OrderItem
      summary: Create a new order item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderItem'
      responses:
        '201':
          description: Order item created.

  /order-items/{id}:
    get:
      tags:
        - OrderItem
      summary: Get an order item by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single order item.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderItem'
    put:
      tags:
        - OrderItem
      summary: Update an existing order item
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderItem'
      responses:
        '200':
          description: Order item updated.
    delete:
      tags:
        - OrderItem
      summary: Delete an order item by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Order item deleted.


components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
          format: float
        description:
          type: string

    PurchaseOrder:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
          enum: [pending, completed, cancelled]
        last_updated:
          type: string
          format: date-time
          description: The date and time when the order was last updated.
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
          description: "Order items associated with this purchase order."

    OrderItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        purchaseOrder:
          $ref: '#/components/schemas/PurchaseOrder'
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
        price:
          type: number
          format: float

